import { Key } from '@scanood/nut-js'
const keymap = new Map([
    ['KeyA', Key.A],
    ['KeyB', Key.B],
    ['KeyC', Key.C],
    ['KeyD', Key.D],
    ['KeyE', Key.E],
    ['KeyF', Key.F],
    ['KeyG', Key.G],
    ['KeyH', Key.H],
    ['KeyI', Key.I],
    ['KeyJ', Key.J],
    ['KeyK', Key.K],
    ['KeyL', Key.L],
    ['KeyM', Key.M],
    ['KeyN', Key.N],
    ['KeyO', Key.O],
    ['KeyP', Key.P],
    ['KeyQ', Key.Q],
    ['KeyR', Key.R],
    ['KeyS', Key.S],
    ['KeyT', Key.T],
    ['KeyU', Key.U],
    ['KeyV', Key.V],
    ['KeyW', Key.W],
    ['KeyX', Key.X],
    ['KeyY', Key.Y],
    ['KeyZ', Key.Z],

    ['Digit0', Key.Num0],
    ['Digit1', Key.Num1],
    ['Digit2', Key.Num2],
    ['Digit3', Key.Num3],
    ['Digit4', Key.Num4],
    ['Digit5', Key.Num5],
    ['Digit6', Key.Num6],
    ['Digit7', Key.Num7],
    ['Digit8', Key.Num8],
    ['Digit9', Key.Num9],

    ['Escape', Key.Escape],
    ['F1', Key.F1],
    ['F2', Key.F2],
    ['F3', Key.F3],
    ['F4', Key.F4],
    ['F5', Key.F5],
    ['F6', Key.F6],
    ['F7', Key.F7],
    ['F8', Key.F8],
    ['F9', Key.F9],
    ['F10', Key.F10],
    ['F11', Key.F11],
    ['F12', Key.F12],
    ['F13', Key.F13],
    ['F14', Key.F14],
    ['F15', Key.F15],
    ['F16', Key.F16],
    ['F17', Key.F17],
    ['F18', Key.F18],
    ['F19', Key.F19],
    ['F20', Key.F20],
    ['F21', Key.F21],
    ['F22', Key.F22],
    ['F23', Key.F23],
    ['F24', Key.F24],
    ['Space', Key.Space],
    ['Backspace', Key.Backspace],
    ['Tab', Key.Tab],
    ['Enter', Key.Enter],

    ['ShiftLeft', Key.LeftShift],
    ['ControlLeft', Key.LeftControl],
    ['AltLeft', Key.LeftAlt],
    ['ShiftRight', Key.RightShift],
    ['ControlRight', Key.RightControl],
    ['AltRight', Key.RightAlt],

    ['ScrollLock', Key.ScrollLock],
    ['CapsLock', Key.CapsLock],


    ['Insert', Key.Insert],
    ['Delete', Key.Delete],
    ['PageUp', Key.PageUp],
    ['PageDown', Key.PageDown],
    ['End', Key.End],
    ['Home', Key.Home],


    ['ArrowLeft', Key.Left],
    ['ArrowUp', Key.Up],
    ['ArrowRight', Key.Right],
    ['ArrowDown', Key.Down],
    ['Backslash', Key.Backslash],
    ['bracketLeft', Key.LeftBracket],
    ['bracketRight', Key.RightBracket],
    ['Minus', Key.Minus],
    ['Equal', Key.Equal],
    ['Semicolon', Key.Semicolon],
    ['Quote', Key.Quote],
    ['Comma', Key.Comma],
    ['Period', Key.Period],
    ['Slash', Key.Slash],
    ['MetaLeft', Key.LeftWin],
    ['MetaRight', Key.RightWin],
    ['printScreen', Key.Print],
    ['pause', Key.Pause],
])

export {
    keymap
}